inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  Exclude:
    - 'db/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'
    - 'config/**/*'

Style/MutableConstant:
  Enabled: true

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/DateTime:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

# We may enable this in the future
Style/FrozenStringLiteralComment:
  Enabled: false

Lint/SuppressedException:
  Enabled: false

Lint/NestedMethodDefinition:
  Enabled: true
  Exclude:
    - 'db/migrate/**/*'

Style/StringLiterals:
  Enabled: true