version: '3.8'
services:
  app:
    build: .
    command: start-local
    env_file: .env
    restart: unless-stopped
    environment:
      DB_HOST: db
      REDIS_HOST: cache
      REDIS_PORT: 6379
    ports:
      - 3000:${EXPOSED_PORT}
    networks:
      standardnotes_proxy:
        aliases:
          - syncing_server
      syncing_server: {}
    volumes:
      - .:/syncing-server

  db:
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    expose:
      - 3306
    ports:
      - 3306
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - syncing_server

  cache:
    image: redis:6.0-alpine
    volumes:
      - ./cache:/data
    expose:
      - 6379
    ports:
      - 6379
    networks:
      - syncing_server

networks:
  syncing_server:
    name: syncing_server
  standardnotes_proxy:
    name: standardnotes
