name: PR

on:
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: "changeme123"
          MYSQL_DATABASE: "standard_notes_db"
          MYSQL_USER: "std_notes_user"
          MYSQL_PASSWORD: "changeme123"
        ports:
        - 3306:3306

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5
    - name: Copy default configuration
      run: cp env.sample .env
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rspec
